import { beforeEach, describe, expect, it } from 'vitest'
import { defaultExerciseConfig } from '../exercise/types'
import { analyzeExerciseCompatibility, applyExercisePurpose } from '../exercise/compatibility'
import { deleteExerciseTemplate, listExerciseTemplates, saveExerciseTemplate } from './repository'

describe('biblioteca de ejercicios',()=>{
  beforeEach(()=>localStorage.clear())
  it('guarda la preparación y elimina configuraciones reutilizables',async()=>{const saved=await saveExerciseTemplate({...applyExercisePurpose(defaultExerciseConfig,'saccades'),name:'Sacadas de prueba',preparationSeconds:20});expect((await listExerciseTemplates()).find(item=>item.id===saved.id)?.config.preparationSeconds).toBe(20);await deleteExerciseTemplate(saved.id);expect((await listExerciseTemplates()).some(item=>item.id===saved.id)).toBe(false)})
  it('incluye RVO x2 horizontal, diagonal y objetivo recordado como predeterminados',async()=>{const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['template-rvo-x2-horizontal','template-rvo-x2-diagonal','template-remembered-target']))})
  it('incluye los tres modos cognitivos como ejercicios concretos y no como diagnósticos',async()=>{const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['template-cognitive-rare-target','template-cognitive-go-no-go','template-cognitive-short-memory']));expect(templates.filter(item=>item.id.startsWith('template-cognitive-')).every(item=>item.config.purpose==='cognitive_visual')).toBe(true)})
  it('incluye progresiones PPPD coherentes y doce exposiciones contextuales graduadas',async()=>{const templates=await listExerciseTemplates();const pppd=templates.filter(item=>item.config.clinicalProtocol==='pppd');expect(pppd).toHaveLength(21);for(const purpose of ['visual_habituation','optokinetic','guided_functional'] as const){const levels=pppd.filter(item=>item.config.purpose===purpose).map(item=>item.config.progressionLevel).sort();expect(levels).toEqual([1,2,3])}const immersive=pppd.filter(item=>item.config.purpose==='immersive_context');expect(immersive).toHaveLength(12);expect(new Set(immersive.map(item=>item.config.progressionLevel))).toEqual(new Set([1,2,3]));expect(pppd.every(item=>item.config.progressionCriteria&&item.config.stopCriteria&&analyzeExerciseCompatibility(item.config).valid)).toBe(true)})
  it('permite guardar una configuración Libre aunque no cumpla una regla clínica o técnica',async()=>{const free={...applyExercisePurpose(defaultExerciseConfig,'custom_free'),name:'Combinación profesional',displayMode:'vr_box' as const,doseMode:'repetitions' as const,advanceMode:'manual' as const,backgroundType:'spiral' as const,backgroundSpeed:80,objectMode:'saccades' as const};const saved=await saveExerciseTemplate(free);expect((await listExerciseTemplates()).find(item=>item.id===saved.id)?.config).toMatchObject({purpose:'custom_free',backgroundType:'spiral',objectMode:'saccades'})})
})
