import { beforeEach, describe, expect, it } from 'vitest'
import { defaultExerciseConfig } from '../exercise/types'
import { analyzeExerciseCompatibility, applyExercisePurpose } from '../exercise/compatibility'
import { deleteExerciseTemplate, listExerciseTemplates, saveExerciseTemplate } from './repository'

describe('biblioteca de ejercicios',()=>{
  beforeEach(()=>localStorage.clear())
  it('guarda la preparación y elimina configuraciones reutilizables',async()=>{const saved=await saveExerciseTemplate({...applyExercisePurpose(defaultExerciseConfig,'saccades'),name:'Sacadas de prueba',preparationSeconds:20});expect((await listExerciseTemplates()).find(item=>item.id===saved.id)?.config.preparationSeconds).toBe(20);await deleteExerciseTemplate(saved.id);expect((await listExerciseTemplates()).some(item=>item.id===saved.id)).toBe(false)})
  it('incluye RVO x2 horizontal, diagonal y objetivo recordado como predeterminados',async()=>{const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['template-rvo-x2-horizontal','template-rvo-x2-diagonal','template-remembered-target']))})
  it('incluye seguimiento lento, imágenes rápidas y tres variantes estroboscópicas válidas',async()=>{const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['template-pursuit-very-slow','template-pursuit-vertical-slow','template-rapid-images-soft','template-rapid-images-medium','template-rapid-images-fast','template-strobe-low','template-strobe-medium','template-strobe-diagonal']));const strobes=templates.filter(item=>item.config.clinicalProtocol==='stroboscopic_experimental');expect(strobes).toHaveLength(3);expect(strobes.every(item=>item.config.strobeEnabled&&analyzeExerciseCompatibility(item.config).valid)).toBe(true)})
  it('agrega cinco plantillas visuales no redundantes y conserva su diferencia clínica',async()=>{const templates=await listExerciseTemplates();const ids=['template-visual-motion-fixation-low','template-pursuit-structured-background','template-visual-motion-oscillating-low','template-pursuit-counterphase-low','template-optic-flow-expansion-low'];expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(ids));const fixation=templates.find(item=>item.id===ids[0]);const structured=templates.find(item=>item.id===ids[1]);const counterphase=templates.find(item=>item.id===ids[3]);const opticFlow=templates.find(item=>item.id===ids[4]);expect(fixation?.config).toMatchObject({purpose:'visual_motion_fixation',objectMode:'fixed',backgroundType:'bars',backgroundSpeed:15,backgroundRampSeconds:2,backgroundCoveragePercent:75,backgroundContrastPercent:60,durationSeconds:20});expect(structured?.config).toMatchObject({purpose:'smooth_pursuit',objectMode:'tracking',backgroundType:'checkerboard',backgroundSpeed:0,backgroundCoveragePercent:100,backgroundContrastPercent:35,durationSeconds:30});expect(counterphase?.config).toMatchObject({purpose:'pursuit_visual_conflict',targetBackgroundRelation:'counter_phase',backgroundMotionMode:'oscillating',backgroundFrequencyHz:0.2,objectSpeedHz:0.2});expect(opticFlow?.config).toMatchObject({purpose:'optic_flow',backgroundType:'radial_flow',backgroundDirection:'toward',objectEnabled:false});expect(ids.every(id=>analyzeExerciseCompatibility(templates.find(item=>item.id===id)!.config).valid)).toBe(true)})
  it('migra nuevas plantillas sin borrar una plantilla personal existente',async()=>{localStorage.setItem('onur-demo-exercise-templates-v1',JSON.stringify([{id:'personal-existing',name:'Plantilla personal',config:{...defaultExerciseConfig,name:'Plantilla personal'},createdAt:'2026-08-01T00:00:00.000Z',updatedAt:'2026-08-01T00:00:00.000Z'}]));localStorage.setItem('onur-demo-exercise-templates-seed-version','8');const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['personal-existing','template-visual-motion-fixation-low','template-pursuit-structured-background','template-visual-motion-oscillating-low','template-pursuit-counterphase-low','template-optic-flow-expansion-low']))})
  it('incluye los tres modos cognitivos como ejercicios concretos y no como diagnósticos',async()=>{const templates=await listExerciseTemplates();expect(templates.map(item=>item.id)).toEqual(expect.arrayContaining(['template-cognitive-rare-target','template-cognitive-go-no-go','template-cognitive-short-memory']));expect(templates.filter(item=>item.id.startsWith('template-cognitive-')).every(item=>item.config.purpose==='cognitive_visual')).toBe(true)})
  it('incluye progresiones PPPD coherentes y doce exposiciones contextuales graduadas',async()=>{const templates=await listExerciseTemplates();const pppd=templates.filter(item=>item.config.clinicalProtocol==='pppd');expect(pppd).toHaveLength(21);for(const purpose of ['visual_habituation','optokinetic','guided_functional'] as const){const levels=pppd.filter(item=>item.config.purpose===purpose).map(item=>item.config.progressionLevel).sort();expect(levels).toEqual([1,2,3])}const immersive=pppd.filter(item=>item.config.purpose==='immersive_context');expect(immersive).toHaveLength(12);expect(new Set(immersive.map(item=>item.config.progressionLevel))).toEqual(new Set([1,2,3]));expect(pppd.every(item=>item.config.progressionCriteria&&item.config.stopCriteria&&analyzeExerciseCompatibility(item.config).valid)).toBe(true)})
  it('permite guardar una configuración Libre aunque no cumpla una regla clínica o técnica',async()=>{const free={...applyExercisePurpose(defaultExerciseConfig,'custom_free'),name:'Combinación profesional',displayMode:'vr_box' as const,doseMode:'repetitions' as const,advanceMode:'manual' as const,backgroundType:'spiral' as const,backgroundSpeed:80,objectMode:'saccades' as const};const saved=await saveExerciseTemplate(free);expect((await listExerciseTemplates()).find(item=>item.id===saved.id)?.config).toMatchObject({purpose:'custom_free',backgroundType:'spiral',objectMode:'saccades'})})
})
