import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { deleteClinicalDocument, listCurrentPatientDocumentCatalog, listPatientDocumentAccessRequests, listPatientDocuments, requestDocumentAccess, resolveDocumentAccessRequest, setDocumentPermission, uploadClinicalDocument } from './repository'
import type { ClinicalDocumentRecord, DocumentPermissionLevel } from './types'

export const documentKeys={patient:(id:string)=>['documents',id] as const,current:['patient-documents'] as const,requests:(id:string)=>['document-access-requests',id] as const}
export function usePatientDocuments(patientId:string){return useQuery({queryKey:documentKeys.patient(patientId),queryFn:()=>listPatientDocuments(patientId),enabled:Boolean(patientId)})}
export function useCurrentPatientDocuments(){return useQuery({queryKey:documentKeys.current,queryFn:listCurrentPatientDocumentCatalog})}
export function useUploadDocument(patientId:string){const client=useQueryClient();return useMutation({mutationFn:uploadClinicalDocument,onSuccess:()=>client.invalidateQueries({queryKey:documentKeys.patient(patientId)})})}
export function useDeleteDocument(patientId:string){const client=useQueryClient();return useMutation({mutationFn:deleteClinicalDocument,onSuccess:(_,document)=>{client.invalidateQueries({queryKey:documentKeys.patient(patientId)});client.invalidateQueries({queryKey:documentKeys.current});client.invalidateQueries({queryKey:documentKeys.requests(patientId)});client.invalidateQueries({queryKey:['studies']});client.invalidateQueries({queryKey:['statistical-suggestions']});for(const studyId of document.studyIds??(document.studyId?[document.studyId]:[])){client.removeQueries({queryKey:['study',studyId]});client.removeQueries({queryKey:['document-extraction',studyId]})}}})}
export function useSetDocumentPermission(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({document,level}:{document:ClinicalDocumentRecord;level:DocumentPermissionLevel|null})=>setDocumentPermission(document,level),onSuccess:()=>{client.invalidateQueries({queryKey:documentKeys.patient(patientId)});client.invalidateQueries({queryKey:documentKeys.current})}})}
export function usePatientDocumentAccessRequests(patientId:string){return useQuery({queryKey:documentKeys.requests(patientId),queryFn:()=>listPatientDocumentAccessRequests(patientId),enabled:Boolean(patientId)})}
export function useRequestDocumentAccess(){const client=useQueryClient();return useMutation({mutationFn:requestDocumentAccess,onSuccess:()=>client.invalidateQueries({queryKey:documentKeys.current})})}
export function useResolveDocumentAccessRequest(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({requestId,decision,level,professionalNote}:{requestId:string;decision:'approved'|'denied';level:DocumentPermissionLevel;professionalNote?:string})=>resolveDocumentAccessRequest(requestId,decision,level,professionalNote),onSuccess:()=>{client.invalidateQueries({queryKey:documentKeys.requests(patientId)});client.invalidateQueries({queryKey:documentKeys.patient(patientId)});client.invalidateQueries({queryKey:documentKeys.current})}})}
