import { useEffect } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { cancelSessionAssignment, completeSessionAssignment, completeSupervisedInPersonSession, createSessionAssignment, createTreatmentCycle, duplicateInPersonAssignmentAsHome, getCurrentPatientAssignment, interruptSessionAssignment, listProfessionalAssignments, listSessionAssignments, listTreatmentCycles, recordFreeInPersonSession, recordRetrospectiveSession, repeatSessionAssignmentAsHome, revokeSessionAssignment, startSessionAssignment, startSupervisedInPersonSession, updateSessionAssignment, type FreeInPersonSessionInput, type RepeatSessionAssignmentInput, type RetrospectiveCompletionInput, type SessionAssignmentRecord, type SessionCompletionInput, type SessionInterruptionInput, type SupervisedSessionCompletionInput } from './repository'
import { flushPendingSessionCompletions, isLikelyNetworkFailure, queueSessionCompletion, queueSessionInterruption } from './offlineQueue'
import { isSupabaseConfigured } from '../../lib/supabase'
import { createQuestSessionPairing, findQuestSessionPairingForAssignment, getQuestSessionPairing, revokeQuestSessionPairing, type QuestPairingCreated } from './questRepository'

export const sessionKeys={cycles:(id:string)=>['cycles',id] as const,assignments:(id:string)=>['assignments',id] as const,all:['assignments'] as const,current:['patient-current-assignment'] as const,questPairing:(id:string)=>['quest-pairing',id] as const,questAssignment:(id:string)=>['quest-assignment',id] as const}
export function useTreatmentCycles(patientId:string){return useQuery({queryKey:sessionKeys.cycles(patientId),queryFn:()=>listTreatmentCycles(patientId),enabled:Boolean(patientId)})}
export function useSessionAssignments(patientId:string){return useQuery({queryKey:sessionKeys.assignments(patientId),queryFn:()=>listSessionAssignments(patientId),enabled:Boolean(patientId)})}
export function useCreateTreatmentCycle(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(values:Parameters<typeof createTreatmentCycle>[1])=>createTreatmentCycle(patientId,values),onSuccess:()=>client.invalidateQueries({queryKey:sessionKeys.cycles(patientId)})})}
export function useCreateSessionAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(values:Parameters<typeof createSessionAssignment>[1])=>createSessionAssignment(patientId,values),onSuccess:()=>client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)})})}
export function useUpdateSessionAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({assignment,values}:{assignment:SessionAssignmentRecord;values:Parameters<typeof updateSessionAssignment>[1]})=>updateSessionAssignment(assignment,values),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useRevokeSessionAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({assignment,reason}:{assignment:SessionAssignmentRecord;reason:string})=>revokeSessionAssignment(assignment,reason),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all});await client.invalidateQueries({queryKey:sessionKeys.current})}})}
export function useCancelSessionAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({assignment,reason}:{assignment:SessionAssignmentRecord;reason:string})=>cancelSessionAssignment(assignment,reason),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all});await client.invalidateQueries({queryKey:sessionKeys.current})}})}
export function useCurrentPatientAssignment(){return useQuery({queryKey:sessionKeys.current,queryFn:getCurrentPatientAssignment})}
export function useProfessionalAssignments(){return useQuery({queryKey:sessionKeys.all,queryFn:listProfessionalAssignments})}
export function useCompleteSession(){const client=useQueryClient();return useMutation({mutationFn:async(input:SessionCompletionInput)=>{if(isSupabaseConfigured&&!navigator.onLine){queueSessionCompletion(input);return{queued:true}}try{await completeSessionAssignment(input);return{queued:false}}catch(error){if(isSupabaseConfigured&&isLikelyNetworkFailure(error)){queueSessionCompletion(input);return{queued:true}}throw error}},onSuccess:()=>client.invalidateQueries({queryKey:sessionKeys.current})})}
export function useInterruptSession(){const client=useQueryClient();return useMutation({mutationFn:async(input:SessionInterruptionInput)=>{if(isSupabaseConfigured&&!navigator.onLine){queueSessionInterruption(input);return{queued:true}}try{await interruptSessionAssignment(input);return{queued:false}}catch(error){if(isSupabaseConfigured&&isLikelyNetworkFailure(error)){queueSessionInterruption(input);return{queued:true}}throw error}},onSuccess:()=>client.invalidateQueries({queryKey:sessionKeys.current})})}
export function useStartSession(){return useMutation({mutationFn:(assignment:SessionAssignmentRecord)=>startSessionAssignment(assignment)})}
export function useStartSupervisedInPersonSession(patientId:string){const client=useQueryClient();return useMutation({mutationFn:({assignment,initialDiscomfort}:{assignment:SessionAssignmentRecord;initialDiscomfort:number})=>startSupervisedInPersonSession(assignment,initialDiscomfort),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useCompleteSupervisedInPersonSession(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(input:SupervisedSessionCompletionInput)=>completeSupervisedInPersonSession(input),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useRecordFreeInPersonSession(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(input:FreeInPersonSessionInput)=>recordFreeInPersonSession(input),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useRecordRetrospectiveSession(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(input:RetrospectiveCompletionInput)=>recordRetrospectiveSession(input),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useDuplicateInPersonAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(assignment:SessionAssignmentRecord)=>duplicateInPersonAssignmentAsHome(assignment),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all})}})}
export function useRepeatSessionAssignment(patientId:string){const client=useQueryClient();return useMutation({mutationFn:(input:RepeatSessionAssignmentInput)=>repeatSessionAssignmentAsHome(input),onSuccess:async()=>{await client.invalidateQueries({queryKey:sessionKeys.assignments(patientId)});await client.invalidateQueries({queryKey:sessionKeys.all});await client.invalidateQueries({queryKey:sessionKeys.current})}})}
export function useCreateQuestSessionPairing(){const client=useQueryClient();return useMutation({mutationFn:(assignment:SessionAssignmentRecord)=>createQuestSessionPairing(assignment),onSuccess:(created:QuestPairingCreated)=>client.setQueryData(sessionKeys.questPairing(created.id),created)})}
export function useQuestSessionPairing(id:string,enabled=true){return useQuery({queryKey:sessionKeys.questPairing(id),queryFn:()=>getQuestSessionPairing(id),enabled:Boolean(id)&&enabled,refetchInterval:(query)=>{const status=query.state.data?.status;return status==='ready'||status==='claimed'?1500:false}})}
export function useQuestSessionPairingForAssignment(assignmentId:string,enabled=true){return useQuery({queryKey:sessionKeys.questAssignment(assignmentId),queryFn:()=>findQuestSessionPairingForAssignment(assignmentId),enabled:Boolean(assignmentId)&&enabled})}
export function useRevokeQuestSessionPairing(){const client=useQueryClient();return useMutation({mutationFn:(id:string)=>revokeQuestSessionPairing(id),onSuccess:(_,id)=>client.invalidateQueries({queryKey:sessionKeys.questPairing(id)})})}

export function usePendingSessionSync(){
  const client=useQueryClient()
  useEffect(()=>{
    const sync=async()=>{const count=await flushPendingSessionCompletions();if(count>0)await client.invalidateQueries({queryKey:sessionKeys.current})}
    void sync()
    window.addEventListener('online',sync)
    return()=>window.removeEventListener('online',sync)
  },[client])
}
