import { beforeEach, describe, expect, it } from 'vitest'
import { defaultExerciseConfig } from '../exercise/types'
import { applyExercisePurpose } from '../exercise/compatibility'
import { completeSessionAssignment, completeSupervisedInPersonSession, createSessionAssignment, createTreatmentCycle, deleteSessionAssignment, duplicateInPersonAssignmentAsHome, getCurrentPatientAssignment, listSessionAssignments, listTreatmentCycles, sessionDurationSeconds, startSessionAssignment, startSupervisedInPersonSession, updateSessionAssignment } from './repository'
import { clearPendingSessionCompletions, isLikelyNetworkFailure, pendingSessionCompletionCount, queueSessionCompletion } from './offlineQueue'

describe('repositorio demo de ciclos y sesiones',()=>{
  beforeEach(()=>localStorage.clear())
  it('crea un ciclo activo para un paciente',async()=>{const created=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'Objetivo',startedOn:'2026-07-16'});expect(created.status).toBe('active');expect(await listTreatmentCycles('patient-new')).toHaveLength(1)})
  it('conserva la configuración y preparación de ejercicios en la asignación',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'Indicaciones',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[{...defaultExerciseConfig,durationSeconds:30,rounds:2,restSeconds:10,preparationSeconds:20}]});expect((await listSessionAssignments('patient-new'))[0].exercises[0]).toMatchObject({durationSeconds:30,preparationSeconds:20});expect(sessionDurationSeconds(assignment)).toBe(70)})
  it('modifica una sesión asignada que todavía no comenzó',async()=>{const cycle=await createTreatmentCycle('patient-edit',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-edit',{title:'Original',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await updateSessionAssignment(assignment,{title:'Actualizada',instructions:'Nueva indicación',mode:'in_person',treatmentCycleId:cycle.id,availableFrom:'2026-07-18',availableUntil:'2026-07-20',exercises:[{...defaultExerciseConfig,name:'Ejercicio actualizado'}]});expect((await listSessionAssignments('patient-edit'))[0]).toMatchObject({id:assignment.id,title:'Actualizada',instructions:'Nueva indicación',mode:'in_person'});expect((await listSessionAssignments('patient-edit'))[0].exercises[0].name).toBe('Ejercicio actualizado')})
  it('elimina una sesión asignada que todavía no comenzó',async()=>{const cycle=await createTreatmentCycle('patient-delete',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-delete',{title:'Eliminar',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await deleteSessionAssignment(assignment);expect(await listSessionAssignments('patient-delete')).toHaveLength(0)})
  it('protege de edición y eliminación una sesión que ya comenzó',async()=>{const cycle=await createTreatmentCycle('patient-protected',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-protected',{title:'Protegida',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await startSessionAssignment(assignment);const started=(await listSessionAssignments('patient-protected'))[0];await expect(updateSessionAssignment(started,{title:'No cambiar',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]})).rejects.toThrow('historial');await expect(deleteSessionAssignment(started)).rejects.toThrow('historial');expect((await listSessionAssignments('patient-protected'))[0].title).toBe('Protegida')})
  it('incluye el tiempo para colocar y retirar VR Box en la duración prevista',async()=>{const cycle=await createTreatmentCycle('patient-vr',{label:'Ciclo VR',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-vr',{title:'Sesión VR',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[{...applyExercisePurpose(defaultExerciseConfig,'optokinetic'),displayMode:'vr_box',advanceMode:'automatic',durationSeconds:30,rounds:1,restSeconds:0}]});expect(sessionDurationSeconds(assignment)).toBe(70)})
  it('guarda el auto-reporte descriptivo al finalizar',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await completeSessionAssignment({assignment,activeSeconds:42.4,skippedExercises:1,initialDiscomfort:3,finalDiscomfort:4,perceivedDifficulty:2,patientComment:'  Todo bien  '});const saved=(await listSessionAssignments('patient-new'))[0];expect(saved).toMatchObject({status:'partial',activeSeconds:42,initialDiscomfort:3,finalDiscomfort:4,perceivedDifficulty:2,patientComment:'Todo bien'})})
  it('registra el inicio sin impedir que la sesión pueda retomarse',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await startSessionAssignment(assignment);expect((await listSessionAssignments('patient-new'))[0].status).toBe('started')})
  it('excluye asignaciones presenciales del portal domiciliario',async()=>{expect((await getCurrentPatientAssignment())?.mode).toBe('home')})
  it('reinicia y completa una sesión presencial supervisada con omisión',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Presencial ficticia',instructions:'',mode:'in_person',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await startSupervisedInPersonSession(assignment,2);const started=(await listSessionAssignments('patient-new'))[0];await startSupervisedInPersonSession(started,4);await completeSupervisedInPersonSession({assignment:started,activeSeconds:31.6,skippedExercises:1,finalDiscomfort:3,perceivedDifficulty:2,patientComment:'  Declaración ficticia  ',professionalObservation:'  Observación ficticia  '});const saved=(await listSessionAssignments('patient-new'))[0];expect(saved).toMatchObject({status:'partial',activeSeconds:32,initialDiscomfort:4,finalDiscomfort:3,perceivedDifficulty:2,patientComment:'Declaración ficticia',professionalObservation:'Observación ficticia',supervised:true,operatedBy:'demo-professional'})})
  it('duplica una presencial como asignación domiciliaria independiente',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Presencial ficticia',instructions:'',mode:'in_person',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});const duplicatedId=await duplicateInPersonAssignmentAsHome(assignment);const saved=await listSessionAssignments('patient-new');expect(saved.find(item=>item.id===duplicatedId)).toMatchObject({mode:'home',status:'assigned',patientId:'patient-new'});expect(duplicatedId).not.toBe(assignment.id)})
  it('mantiene una sola finalización pendiente por asignación',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});const input={assignment,activeSeconds:20,skippedExercises:0,initialDiscomfort:1,finalDiscomfort:1,perceivedDifficulty:2,patientComment:''};queueSessionCompletion(input);queueSessionCompletion({...input,activeSeconds:25});expect(pendingSessionCompletionCount()).toBe(1);clearPendingSessionCompletions();expect(pendingSessionCompletionCount()).toBe(0)})
  it('distingue una caída de red de un error de autorización',()=>{expect(isLikelyNetworkFailure(new TypeError('Failed to fetch'))).toBe(true);expect(isLikelyNetworkFailure(new Error('Asignación no disponible.'))).toBe(false)})
})
