import { ChevronLeft, FileDown, ImagePlus, Save } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useCreateAssessment } from '../features/assessments/hooks'
import { assessmentDomains, assessmentOptions, assessmentPhaseLabels, assessmentQuestions } from '../features/assessments/questions'
import type { AssessmentPhase, AssessmentResponse } from '../features/assessments/repository'
import { useUploadDocument } from '../features/documents/hooks'
import { usePatient } from '../features/patients/hooks'
import { useTreatmentCycles } from '../features/sessions/hooks'

export function AssessmentFormPage(){
  const{patientId=''}=useParams();const[params]=useSearchParams();const navigate=useNavigate();const{data:patient}=usePatient(patientId);const{data:cycles=[]}=useTreatmentCycles(patientId);const create=useCreateAssessment(patientId);const upload=useUploadDocument(patientId)
  const[phase,setPhase]=useState<AssessmentPhase>((params.get('phase') as AssessmentPhase)||'initial');const[cycleId,setCycleId]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[responses,setResponses]=useState<AssessmentResponse[]>(Array(18).fill(null));const[generalRating,setGeneralRating]=useState<number|null>(null);const[fallsCount,setFallsCount]=useState<number|null>(null);const[walkingAidUsed,setWalkingAidUsed]=useState<boolean|null>(null);const[photo,setPhoto]=useState<File|null>(null);const[error,setError]=useState('')
  useEffect(()=>{setCycleId(cycles.find(cycle=>cycle.status==='active')?.id??cycles[0]?.id??'')},[cycles])
  const answered=responses.filter(value=>value!==null).length;const applicable=responses.filter((value):value is number=>typeof value==='number');const total=applicable.reduce((sum,value)=>sum+value,0);const maximum=applicable.length*3
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!cycleId){setError('Seleccioná un ciclo de tratamiento.');return}setError('');try{let sourceDocumentId='';if(photo){const document=await upload.mutateAsync({patientId,treatmentCycleId:cycleId,documentType:phase==='initial'?'questionnaire_initial':phase==='final'?'questionnaire_final':'other',documentDate:date,description:`Cuestionario ${assessmentPhaseLabels[phase].toLowerCase()} completado en papel.`,shareWithPatient:false,file:photo,deviceName:'',protocolCode:'',protocolVersion:'1'});sourceDocumentId=document.id}await create.mutateAsync({patientId,treatmentCycleId:cycleId,sourceDocumentId,phase,assessmentDate:date,responses,generalRating,fallsCount,walkingAidUsed});navigate(`/app/pacientes/${patientId}`,{state:{notice:'Evaluación guardada correctamente.'}})}catch(caught){setError(caught instanceof Error?caught.message:'No fue posible guardar la evaluación.')}}
  return <div className="space-y-7"><Link to={`/app/pacientes/${patientId}`} className="inline-flex items-center gap-2 text-xs font-black text-[#E49A02]"><ChevronLeft size={16}/> Volver al perfil</Link><PageHeader eyebrow="Evaluación de percepción" title="Transcribir cuestionario" description={patient?`Registro profesional de la hoja completada por ${patient.fullName}.`:'Registro profesional del cuestionario físico.'} actions={<a href={`${import.meta.env.BASE_URL}resources/cuestionario-percepcion-onur.pdf`} target="_blank" className="inline-flex items-center gap-2 rounded-2xl border border-[#E9E7E7] bg-white px-4 py-3 text-sm font-black text-[#2F2F2F]"><FileDown size={17}/> Imprimir formulario</a>}/>
    <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1fr_300px]"><section className="space-y-4"><div className="grid gap-4 rounded-2xl border border-[#E9E7E7] bg-white p-5 sm:grid-cols-3"><label className="text-xs font-black text-[#2F2F2F]">Momento<select className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={phase} onChange={event=>setPhase(event.target.value as AssessmentPhase)}><option value="initial">Inicial</option><option value="final">Final</option><option value="follow_up">Seguimiento</option></select></label><label className="text-xs font-black text-[#2F2F2F]">Ciclo<select className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={cycleId} onChange={event=>setCycleId(event.target.value)}><option value="">Seleccionar…</option>{cycles.map(cycle=><option key={cycle.id} value={cycle.id}>{cycle.label}</option>)}</select></label><label className="text-xs font-black text-[#2F2F2F]">Fecha<input type="date" className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={date} onChange={event=>setDate(event.target.value)}/></label></div>
      {assessmentQuestions.map((question,index)=>{const domain=assessmentDomains.find(item=>item.start===index);const questionLabelId=`assessment-question-${index+1}`;return <div key={question} className="space-y-3">{domain&&<h2 className="px-1 pt-2 text-lg font-black text-[#171717]">{domain.label}</h2>}<fieldset aria-labelledby={questionLabelId} className="rounded-2xl border border-[#E9E7E7] bg-white p-5"><p id={questionLabelId} className="text-sm font-black leading-6 text-[#2F2F2F]">{index+1}. {question}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{assessmentOptions.map(option=><label key={option.value} className={`cursor-pointer rounded-2xl border p-3 text-center text-xs font-bold ${responses[index]===option.value?'border-[#E49A02] bg-[#FFF7E8] text-[#7A5100]':'border-[#E9E7E7] text-[#747474]'}`}><input type="radio" className="sr-only" name={`question-${index}`} checked={responses[index]===option.value} onChange={()=>setResponses(values=>values.map((value,itemIndex)=>itemIndex===index?option.value:value))}/><span className="block text-base font-black">{option.value==='not_applicable'?'—':option.value}</span>{option.label}</label>)}</div><button type="button" onClick={()=>setResponses(values=>values.map((value,itemIndex)=>itemIndex===index?null:value))} className="mt-3 text-[11px] font-bold text-[#747474]">Dejar sin transcribir</button></fieldset></div>})}
      <section className="rounded-2xl border border-[#E9E7E7] bg-white p-5"><h2 className="text-lg font-black text-[#171717]">Datos complementarios declarados</h2><p className="mt-1 text-xs leading-5 text-[#747474]">Período de referencia: últimos 7 días.</p><div className="mt-5 grid gap-5 sm:grid-cols-3"><label className="text-xs font-black text-[#2F2F2F]">Estado general (0–10)<select className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={generalRating??''} onChange={event=>setGeneralRating(event.target.value===''?null:Number(event.target.value))}><option value="">No transcrito</option>{Array.from({length:11},(_,value)=><option key={value} value={value}>{value}</option>)}</select></label><label className="text-xs font-black text-[#2F2F2F]">Caídas declaradas<input type="number" min="0" className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={fallsCount??''} onChange={event=>setFallsCount(event.target.value===''?null:Math.max(0,Number(event.target.value)))}/></label><label className="text-xs font-black text-[#2F2F2F]">Usó apoyo para caminar<select className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={walkingAidUsed===null?'':walkingAidUsed?'yes':'no'} onChange={event=>setWalkingAidUsed(event.target.value===''?null:event.target.value==='yes')}><option value="">No transcrito</option><option value="no">No</option><option value="yes">Sí</option></select></label></div></section>
    </section><aside className="space-y-5 xl:sticky xl:top-24 xl:self-start"><section className="rounded-2xl border border-[#E9E7E7] bg-white p-6"><p className="text-xs font-black uppercase tracking-[.15em] text-[#E49A02]">Resumen descriptivo</p><p className="mt-3 text-4xl font-black text-[#171717]">{total}<span className="text-lg text-[#747474]">/{maximum}</span></p><p className="mt-2 text-xs text-[#747474]">{answered}/18 respuestas · {applicable.length} puntuables</p><p className="mt-4 rounded-2xl bg-[#FFF7E8] p-3 text-xs leading-5 text-[#8A5B00]">El total solo resume las respuestas aplicables. No tiene puntos de corte, no es diagnóstico y se compara únicamente dentro de la misma persona.</p></section><label className="block cursor-pointer rounded-2xl border-2 border-dashed border-[#E8CE99] bg-white p-6 text-center"><ImagePlus className="mx-auto text-[#E49A02]"/><strong className="mt-3 block text-sm text-[#2F2F2F]">{photo?photo.name:'Adjuntar foto de la hoja'}</strong><small className="mt-1 block text-[#747474]">Opcional, queda privada</small><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="sr-only" onChange={event=>setPhoto(event.target.files?.[0]??null)}/></label>{error&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952]">{error}</p>}<button disabled={create.isPending||upload.isPending} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#E49A02] px-5 py-4 text-sm font-black text-white"><Save size={17}/>{create.isPending||upload.isPending?'Guardando…':'Guardar evaluación'}</button></aside></form>
  </div>
}
