import { BarChart3, CheckCircle2, ClipboardList, Clock3, Home, MonitorPlay, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { useProfessionalAssessments } from '../features/assessments/hooks'
import { usePatients } from '../features/patients/hooks'
import { useProfessionalAssignments } from '../features/sessions/hooks'
import { buildProfessionalStatistics, type StatisticsPeriod } from '../features/statistics/analytics'

const statusLabels={completed:'Completadas',partial:'Parciales',assigned:'Asignadas',started:'Iniciadas',interrupted:'Interrumpidas',omitted:'Omitidas'} as const

export function StatisticsPage(){
  const[period,setPeriod]=useState<StatisticsPeriod>('all');const[patientId,setPatientId]=useState('')
  const{data:patients=[],isPending:patientsPending}=usePatients();const{data:assignments=[],isPending:sessionsPending}=useProfessionalAssignments();const{data:assessments=[],isPending:assessmentsPending}=useProfessionalAssessments()
  const statistics=useMemo(()=>buildProfessionalStatistics(assignments,assessments,patients,{period,patientId}),[assignments,assessments,patients,period,patientId]);const pending=patientsPending||sessionsPending||assessmentsPending
  const maxMonthly=Math.max(1,...statistics.activityByMonth.map(item=>item.assigned));const maxStatus=Math.max(1,...statistics.statusRows.map(item=>item.count))
  return <div className="space-y-7"><PageHeader eyebrow="Seguimiento operativo" title="Estadísticas" description="Lectura descriptiva de sesiones y cuestionarios registrados. No aplica normas clínicas, diagnósticos ni recomendaciones automáticas." actions={<><label className="grid gap-1 text-[10px] font-black uppercase tracking-[.12em] text-[#747474]">Paciente<select value={patientId} onChange={event=>setPatientId(event.target.value)} className="h-11 min-w-48 rounded-2xl border border-[#E9E7E7] bg-white px-3 text-xs font-bold normal-case tracking-normal text-[#2F2F2F]"><option value="">Todos</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.fullName}</option>)}</select></label><label className="grid gap-1 text-[10px] font-black uppercase tracking-[.12em] text-[#747474]">Período<select value={period} onChange={event=>setPeriod(event.target.value as StatisticsPeriod)} className="h-11 rounded-2xl border border-[#E9E7E7] bg-white px-3 text-xs font-bold normal-case tracking-normal text-[#2F2F2F]"><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="all">Todo el historial</option></select></label></>}/>
    {pending?<div className="grid min-h-64 place-items-center rounded-2xl border border-[#E9E7E7] bg-white text-sm font-bold text-[#747474]">Calculando estadísticas…</div>:<>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={MonitorPlay} label="Sesiones del período" value={String(statistics.totals.sessions)} detail={`${statistics.modes.home} domiciliarias · ${statistics.modes.inPerson} presenciales`} tone="blue"/><StatCard icon={CheckCircle2} label="Registradas como realizadas" value={`${statistics.totals.realizationRate}%`} detail={`${statistics.totals.completed} completas · ${statistics.totals.partial} parciales`}/><StatCard icon={Clock3} label="Tiempo activo" value={`${statistics.totals.activeMinutes} min`} detail={statistics.totals.averageActiveProgress===null?'Sin ejecuciones con duración':'Promedio '+statistics.totals.averageActiveProgress+'% del tiempo planificado'} tone="amber"/><StatCard icon={ClipboardList} label="Cuestionarios DHI" value={String(statistics.totals.evaluations)} detail={`${statistics.totals.completeEvaluations} completados`} tone="rose"/></section>
      <aside className="rounded-2xl border border-[#E8CE99] bg-[#FFF7E8] px-5 py-4 text-xs leading-5 text-[#6F5A2A]"><strong className="text-[#7A5100]">Cómo leer este tablero:</strong> “realizada” agrupa sesiones completas y parciales. Los porcentajes describen registros de ONUr; no miden recuperación, eficacia terapéutica ni condición clínica.</aside>
      <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-2xl border border-[#E9E7E7] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#F1EFEC] text-[#5E5E5E]"><BarChart3 size={18}/></span><div><h2 className="text-lg font-black text-[#171717]">Actividad por mes</h2><p className="text-xs text-[#747474]">Asignadas frente a registradas como realizadas</p></div></div>{statistics.activityByMonth.length===0?<p className="mt-6 rounded-2xl bg-[#F7F6F4] p-5 text-sm text-[#747474]">No hay sesiones en el período elegido.</p>:<div className="mt-6 flex h-52 items-end gap-3 border-b border-[#E9E7E7] pb-2">{statistics.activityByMonth.map(item=><div key={item.key} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="flex h-36 w-full items-end justify-center gap-1"><span title={`${item.assigned} asignadas`} className="w-3 max-w-[28%] rounded-t bg-[#E9E7E7]" style={{height:`${Math.max(7,item.assigned/maxMonthly*100)}%`}}/><span title={`${item.realized} realizadas`} className="w-3 max-w-[28%] rounded-t bg-[#E49A02]" style={{height:`${Math.max(item.realized?7:0,item.realized/maxMonthly*100)}%`}}/></div><span className="truncate text-[10px] font-bold capitalize text-[#747474]">{item.label}</span></div>)}</div>}<div className="mt-4 flex gap-5 text-[10px] font-bold text-[#747474]"><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[#E9E7E7]"/>Asignadas</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[#E49A02]"/>Realizadas</span></div></article>
        <article className="rounded-2xl border border-[#E9E7E7] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#FFF7E8] text-[#E49A02]"><CheckCircle2 size={18}/></span><div><h2 className="text-lg font-black text-[#171717]">Estado de las sesiones</h2><p className="text-xs text-[#747474]">Conteo sin asignaciones revocadas</p></div></div>{statistics.statusRows.length===0?<p className="mt-6 rounded-2xl bg-[#F7F6F4] p-5 text-sm text-[#747474]">No hay estados para mostrar.</p>:<div className="mt-6 space-y-4">{statistics.statusRows.map(item=><div key={item.status}><div className="flex justify-between text-xs"><span className="font-bold text-[#747474]">{statusLabels[item.status]}</span><strong className="text-[#171717]">{item.count}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#E9E7E7]"><div className="h-full rounded-full bg-[#E49A02]" style={{width:`${item.count/maxStatus*100}%`}}/></div></div>)}</div>}</article></section>
      <section className="overflow-hidden rounded-2xl border border-[#E9E7E7] bg-white"><div className="flex items-center justify-between border-b border-[#E9E7E7] p-6"><div><h2 className="text-lg font-black text-[#171717]">Resumen por paciente</h2><p className="mt-1 text-xs text-[#747474]">La variación del cuestionario es matemática, sin interpretación clínica.</p></div><Users size={20} className="text-[#E49A02]"/></div>{statistics.patientRows.length===0?<p className="p-8 text-sm text-[#747474]">No hay actividad en el período elegido.</p>:<div className="divide-y divide-[#E9E7E7]">{statistics.patientRows.map(row=><Link key={row.patientId} to={`/app/pacientes/${row.patientId}`} className="grid gap-3 px-6 py-5 hover:bg-[#F7F6F4] md:grid-cols-[1.4fr_.7fr_.7fr_.7fr_.8fr] md:items-center"><strong className="text-sm text-[#2F2F2F]">{row.patientName}</strong><span className="text-xs text-[#747474]">{row.realized}/{row.assigned} realizadas</span><span className="text-xs text-[#747474]">{row.activeMinutes} min activos</span><span className="text-xs text-[#747474]">{row.realizationRate===null?'—':row.realizationRate+'%'}</span><span className={`text-xs font-black ${row.questionnaireDifference===null?'text-[#747474]':row.questionnaireDifference>0?'text-[#8A5B00]':'text-[#E49A02]'}`}>{row.questionnaireDifference===null?'Sin par inicial/final':`${row.questionnaireDifference>0?'+':''}${row.questionnaireDifference} puntos`}</span></Link>)}</div>}</section>
      <section className="grid gap-5 lg:grid-cols-[1fr_.75fr]"><article className="rounded-2xl border border-[#E9E7E7] bg-white p-6"><h2 className="text-lg font-black text-[#171717]">Comparaciones DHI</h2><p className="mt-1 text-xs leading-5 text-[#747474]">Solo pares inicial/final completos de la misma versión del DHI y dentro del mismo ciclo.</p>{statistics.assessmentComparisons.length===0?<p className="mt-5 rounded-2xl bg-[#F7F6F4] p-5 text-sm text-[#747474]">Todavía no hay pares completos en el período seleccionado.</p>:<div className="mt-5 divide-y divide-[#E9E7E7]">{statistics.assessmentComparisons.slice(0,8).map(item=><div key={`${item.patientId}-${item.treatmentCycleId}`} className="flex items-center justify-between gap-4 py-4"><div><Link to={`/app/pacientes/${item.patientId}`} className="text-sm font-black text-[#2F2F2F]">{item.patientName}</Link><p className="mt-1 text-xs text-[#747474]">{item.initialDate} → {item.finalDate} · DHI 25 preguntas</p></div><div className="text-right"><p className="text-sm font-black text-[#171717]">{item.initialTotal}/100 → {item.finalTotal}/100</p><p className="mt-1 text-xs font-bold text-[#747474]">{item.difference>0?'+':''}{item.difference} puntos</p></div></div>)}</div>}</article><article className="rounded-2xl border border-[#E9E7E7] bg-[#171717] p-6 text-white"><Home size={22} className="text-[#E49A02]"/><h2 className="mt-5 text-lg font-black">Límites del análisis</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-white/68"><li>• No compara con población normativa.</li><li>• No atribuye cambios al entrenamiento.</li><li>• No reemplaza revisión de estudios o entrevista.</li><li>• No publica sugerencias al paciente.</li></ul></article></section>
    </>}</div>
}
