import { CheckCircle2, FileSearch, Filter, LockKeyhole, Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { StatusBadge } from '../components/StatusBadge'
import { useClinicalStudies } from '../features/studies/hooks'
import type { ClinicalStudyReview, StudyType } from '../features/studies/types'
import { cycleStudyPhaseLabels } from '../features/documents/types'

const typeLabels:Record<StudyType,string>={posturography:'Posturografía',vhit:'vHIT'}

export function StudiesPage(){const{data:studies=[],isPending,error}=useClinicalStudies();const[search,setSearch]=useState('');const[type,setType]=useState<StudyType|''>('');const[status,setStatus]=useState<ClinicalStudyReview['status']|''>('');const filtered=useMemo(()=>{const needle=search.trim().toLocaleLowerCase('es');return studies.filter(item=>(!needle||`${item.patientName} ${item.sourceFilename} ${item.protocolCode}`.toLocaleLowerCase('es').includes(needle))&&(!type||item.studyType===type)&&(!status||item.status===status))},[search,status,studies,type]);return <div className="space-y-7"><PageHeader eyebrow="Registro estructurado" title="Estudios" description="Posturografías y vHIT cargados, revisados o finalizados. Las conclusiones estadísticas permanecen separadas y requieren revisión profesional." actions={<Link to="/app/estudios/importar" className="inline-flex items-center gap-2 rounded-2xl bg-[#E49A02] px-4 py-3 text-sm font-black text-white"><Plus size={17}/> Importar estudio</Link>}/>
  <section className="grid gap-4 lg:grid-cols-3"><Link to="/app/estudios/importar?kind=bap&phase=initial" className="rounded-2xl border-2 border-[#E8CE99] bg-[#FFF7E8] p-5 transition hover:border-[#E49A02]"><FileSearch className="text-[#E49A02]" size={23}/><strong className="mt-3 block text-sm font-black text-[#171717]">Posturografía inicial</strong><span className="mt-1 block text-xs leading-5 text-[#747474]">Subí el estudio externo y asocialo al comienzo del ciclo.</span><span className="mt-3 block text-xs font-black text-[#E49A02]">Cargar inicial →</span></Link><Link to="/app/estudios/importar?kind=bap&phase=final" className="rounded-2xl border-2 border-[#E8CE99] bg-[#FFF7E8] p-5 transition hover:border-[#E49A02]"><FileSearch className="text-[#E49A02]" size={23}/><strong className="mt-3 block text-sm font-black text-[#171717]">Posturografía final</strong><span className="mt-1 block text-xs leading-5 text-[#747474]">Conservá la reevaluación final dentro del mismo ciclo.</span><span className="mt-3 block text-xs font-black text-[#E49A02]">Cargar final →</span></Link><Link to="/app/estudios/importar?kind=vestibular" className="rounded-2xl border-2 border-[#E9E7E7] bg-white p-5 transition hover:border-[#747474]"><FileSearch className="text-[#5E5E5E]" size={23}/><strong className="mt-3 block text-sm font-black text-[#171717]">vHIT / informe vestibular</strong><span className="mt-1 block text-xs leading-5 text-[#747474]">Reuní varios PDF o imágenes en una sola carga.</span><span className="mt-3 block text-xs font-black text-[#5E5E5E]">Cargar estudio →</span></Link></section>
  <section className="grid gap-4 sm:grid-cols-3"><StatCard icon={FileSearch} label="Total" value={String(studies.length)} detail={`${studies.filter(item=>item.studyType==='posturography').length} posturografías · ${studies.filter(item=>item.studyType==='vhit').length} vHIT`} tone="blue"/><StatCard icon={CheckCircle2} label="Revisados" value={String(studies.filter(item=>item.status==='reviewed').length)} detail="Disponibles para finalizar"/><StatCard icon={LockKeyhole} label="Finalizados" value={String(studies.filter(item=>item.status==='finalized').length)} detail="Contenido bloqueado" tone="amber"/></section>
  <section className="rounded-2xl border border-[#E9E7E7] bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_190px_190px]"><label className="relative"><span className="sr-only">Buscar estudios</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#747474]" size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} className="h-12 w-full rounded-2xl border border-[#E9E7E7] pl-11 pr-4 text-sm" placeholder="Buscar paciente, archivo o protocolo"/></label><label className="relative"><Filter className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#747474]" size={15}/><select aria-label="Filtrar por tipo" value={type} onChange={event=>setType(event.target.value as StudyType|'')} className="h-12 w-full rounded-2xl border border-[#E9E7E7] bg-white pl-9 pr-3 text-xs font-bold text-[#747474]"><option value="">Todos los tipos</option><option value="posturography">Posturografía</option><option value="vhit">vHIT</option></select></label><select aria-label="Filtrar por estado" value={status} onChange={event=>setStatus(event.target.value as ClinicalStudyReview['status']|'')} className="h-12 rounded-2xl border border-[#E9E7E7] bg-white px-3 text-xs font-bold text-[#747474]"><option value="">Todos los estados</option><option value="draft">Borrador</option><option value="reviewed">Revisado</option><option value="finalized">Finalizado</option></select></div></section>
  <section className="overflow-hidden rounded-2xl border border-[#E9E7E7] bg-white"><div className="hidden grid-cols-[1.1fr_.8fr_.8fr_.8fr_.6fr] gap-4 bg-[#F7F6F4] px-6 py-3 text-[10px] font-black uppercase tracking-[.12em] text-[#747474] md:grid"><span>Paciente / estudio</span><span>Fecha</span><span>Protocolo</span><span>Datos</span><span>Estado</span></div>{isPending?<p className="p-8 text-sm text-[#747474]">Cargando estudios…</p>:error?<p role="alert" className="p-8 text-sm font-bold text-[#a94952]">{error instanceof Error?error.message:'No fue posible cargar los estudios.'}</p>:filtered.length===0?<p className="p-8 text-sm text-[#747474]">No hay estudios que coincidan con los filtros.</p>:<div className="divide-y divide-[#E9E7E7]">{filtered.map(item=><Link key={item.id} to={`/app/estudios/${item.id}/revisar`} className="grid gap-3 px-6 py-5 hover:bg-[#F7F6F4] md:grid-cols-[1.1fr_.8fr_.8fr_.8fr_.6fr] md:items-center"><div><p className="text-sm font-black text-[#2F2F2F]">{item.patientName}</p><p className="mt-1 truncate text-xs text-[#747474]">{typeLabels[item.studyType]}{item.studyType==='posturography'&&item.cyclePhase!=='unspecified'?` · ${cycleStudyPhaseLabels[item.cyclePhase]}`:''} · {item.sourceFilename}</p></div><span className="text-xs text-[#747474]">{item.performedAt.slice(0,10)}</span><span className="text-xs text-[#747474]">{item.protocolCode} · v{item.protocolVersion}</span><span className="text-xs text-[#747474]">{item.metricCount} métricas · {item.issueCount} incidencias</span><StatusBadge status={item.status}/></Link>)}</div>}</section>
  <p className="text-xs leading-5 text-[#747474]">“Finalizado” describe la integridad del registro. No significa validación diagnóstica ni interpretación clínica automática.</p></div>}
