import { ChevronLeft, FileCheck2, Printer, Save } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { assessmentComparison } from '../features/assessments/repository'
import { usePatientAssessments } from '../features/assessments/hooks'
import { usePatientDocuments } from '../features/documents/hooks'
import { documentTypeLabels } from '../features/documents/types'
import { usePatient } from '../features/patients/hooks'
import { useCreateReport } from '../features/reports/hooks'
import { sessionReportSnapshotItem } from '../features/reports/sessionSnapshot'
import { useSessionAssignments, useTreatmentCycles } from '../features/sessions/hooks'
import { useStatisticalSuggestions } from '../features/studies/hooks'

export function TreatmentReportPage(){
  const{patientId=''}=useParams();const navigate=useNavigate();const{data:patient}=usePatient(patientId);const{data:cycles=[]}=useTreatmentCycles(patientId);const{data:sessions=[]}=useSessionAssignments(patientId);const{data:documents=[]}=usePatientDocuments(patientId);const{data:assessments=[]}=usePatientAssessments(patientId);const{data:suggestions=[]}=useStatisticalSuggestions();const create=useCreateReport(patientId);const[cycleId,setCycleId]=useState('');const[summary,setSummary]=useState('');const[selectedSuggestionIds,setSelectedSuggestionIds]=useState<string[]>([]);const[error,setError]=useState('')
  const selectedCycle=cycles.find(cycle=>cycle.id===(cycleId||cycles.find(item=>item.status==='active')?.id||cycles[0]?.id));const selectedId=selectedCycle?.id??'';const cycleSessions=sessions.filter(item=>item.treatmentCycleId===selectedId);const cycleDocuments=documents.filter(item=>item.treatmentCycleId===selectedId);const cycleAssessments=assessments.filter(item=>item.treatmentCycleId===selectedId);const comparison=assessmentComparison(assessments,selectedId);const reviewedSuggestions=suggestions.filter(item=>item.patientId===patientId&&item.treatmentCycleId===selectedId&&['accepted','edited'].includes(item.status));const includedSuggestions=reviewedSuggestions.filter(item=>selectedSuggestionIds.includes(item.id))
  const snapshot=useMemo(()=>({generatedAt:new Date().toISOString(),cycle:{id:selectedId,label:selectedCycle?.label??'',startedOn:selectedCycle?.startedOn??'',status:selectedCycle?.status??''},sessions:cycleSessions.map(sessionReportSnapshotItem),documents:cycleDocuments.map(item=>({type:item.documentType,date:item.documentDate,filename:item.originalFilename,description:item.description})),assessments:cycleAssessments.map(item=>({instrument:item.instrumentCode,version:item.instrumentVersion,phase:item.phase,date:item.assessmentDate,total:item.totalScore,answered:item.answeredCount,applicable:item.applicableCount,generalRating:item.generalRating,fallsCount:item.fallsCount,walkingAidUsed:item.walkingAidUsed})),comparison:comparison?{initial:comparison.initialComparableTotal,final:comparison.finalComparableTotal,maximum:comparison.maximumScore,comparedQuestions:comparison.comparedCount,difference:comparison.difference}:null,reviewedFindings:includedSuggestions.map(item=>({suggestionId:item.id,studyId:item.studyId,ruleCode:item.ruleCode,text:item.professionalText||item.summary,limitation:item.limitation,status:item.status}))}),[comparison,cycleAssessments,cycleDocuments,cycleSessions,includedSuggestions,selectedCycle,selectedId])
  const save=async(status:'draft'|'final')=>{if(!selectedId){setError('Seleccioná un ciclo.');return}setError('');try{await create.mutateAsync({patientId,treatmentCycleId:selectedId,professionalSummary:summary,snapshot,status});navigate(`/app/pacientes/${patientId}`,{state:{notice:status==='final'?'Informe final versionado.':'Borrador de informe guardado.'}})}catch(caught){setError(caught instanceof Error?caught.message:'No fue posible guardar el informe.')}}
  const complete=cycleSessions.filter(item=>item.status==='completed').length;const partial=cycleSessions.filter(item=>item.status==='partial').length;const revoked=cycleSessions.filter(item=>item.status==='revoked').length
  return <div className="space-y-7 print:bg-white"><Link to={`/app/pacientes/${patientId}`} className="inline-flex items-center gap-2 text-xs font-black text-[#E49A02] print:hidden"><ChevronLeft size={16}/> Volver al perfil</Link><PageHeader eyebrow="Informe por ciclo" title="Resumen de seguimiento" description="Documento descriptivo preparado por el profesional. ONUr no genera conclusiones clínicas automáticas." actions={<><button type="button" onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-2xl border border-[#E9E7E7] bg-white px-4 py-3 text-sm font-black text-[#2F2F2F] print:hidden"><Printer size={17}/> Imprimir / PDF</button></>}/>
    <section className="rounded-2xl border border-[#E9E7E7] bg-white p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#747474]">Paciente</p><p className="mt-2 text-lg font-black text-[#171717]">{patient?.fullName??'Paciente'}</p></div><label className="print:hidden"><span className="text-[10px] font-black uppercase tracking-[.14em] text-[#747474]">Ciclo</span><select className="mt-2 h-11 w-full rounded-2xl border border-[#E9E7E7] px-3 text-sm" value={selectedId} onChange={event=>setCycleId(event.target.value)}>{cycles.map(cycle=><option key={cycle.id} value={cycle.id}>{cycle.label}</option>)}</select></label><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#747474]">Período</p><p className="mt-2 text-sm font-bold text-[#2F2F2F]">Desde {selectedCycle?.startedOn??'-'} · {selectedCycle?.status??'-'}</p></div></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-5">{[['Sesiones',cycleSessions.length],['Completadas',complete],['Parciales',partial],['Anuladas',revoked],['Documentos',cycleDocuments.length]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-[#F7F6F4] p-4"><p className="text-2xl font-black text-[#171717]">{value}</p><p className="mt-1 text-xs text-[#747474]">{label}</p></div>)}</div>
      <div className="mt-8 grid gap-6 lg:grid-cols-2"><article><h2 className="text-lg font-black text-[#171717]">Evaluación percibida</h2>{comparison?<div className="mt-4 rounded-2xl bg-[#FFF7E8] p-5"><p className="text-2xl font-black text-[#7A5100]">{comparison.initialComparableTotal}/{comparison.maximumScore} → {comparison.finalComparableTotal}/{comparison.maximumScore}</p><p className="mt-2 text-sm text-[#6F5A2A]">Diferencia descriptiva: {comparison.difference>0?'+':''}{comparison.difference} puntos sobre {comparison.comparedCount} preguntas comparables.</p></div>:<p className="mt-4 text-sm text-[#747474]">No hay una evaluación inicial y final v2 completas para comparar.</p>}<p className="mt-3 text-xs leading-5 text-[#747474]">Comparación de respuestas autoinformadas aplicables en ambos momentos. No constituye diagnóstico ni atribuye cambios al entrenamiento.</p></article><article><h2 className="text-lg font-black text-[#171717]">Documentos del ciclo</h2><div className="mt-4 space-y-2">{cycleDocuments.length===0?<p className="text-sm text-[#747474]">Sin documentos asociados.</p>:cycleDocuments.map(item=><div key={item.id} className="rounded-2xl border border-[#E9E7E7] p-3"><p className="text-sm font-black text-[#2F2F2F]">{documentTypeLabels[item.documentType]}</p><p className="mt-1 text-xs text-[#747474]">{item.documentDate} · {item.originalFilename}</p></div>)}</div></article></div>
      <article className="mt-8"><h2 className="text-lg font-black text-[#171717]">Sesiones realizadas y asignadas</h2><div className="mt-4 divide-y divide-[#E9E7E7]">{cycleSessions.length===0?<p className="text-sm text-[#747474]">Sin sesiones en este ciclo.</p>:cycleSessions.map(item=><div key={item.id} className={`py-3 text-sm ${item.status==='revoked'?'text-[#747474] opacity-65 grayscale':''}`}><div className="grid gap-2 sm:grid-cols-[1fr_.6fr_.5fr]"><strong className="text-[#2F2F2F]">{item.title}</strong><span className="text-[#747474]">{item.mode==='home'?'Domiciliaria':'Presencial'}</span><span className="font-bold text-[#747474]">{item.status==='revoked'?'Anulada':item.status}</span></div>{item.status==='revoked'&&<p className="mt-2 rounded-xl bg-[#F1EFEC] px-3 py-2 text-xs font-bold leading-5 text-[#5E5E5E]">Motivo de anulación: {item.revokedReason || 'Sin motivo disponible en el registro anterior.'}{item.revokedAt?` · ${new Date(item.revokedAt).toLocaleString('es-UY')}`:''}</p>}{item.initialDiscomfort!==null&&<p className="mt-2 text-xs text-[#747474]">Auto-reporte: malestar {item.initialDiscomfort} → {item.finalDiscomfort} · dificultad {item.perceivedDifficulty}/5{item.patientComment?` · “${item.patientComment}”`:''}</p>}</div>)}</div><p className="mt-3 text-xs leading-5 text-[#747474]">Las sesiones anuladas permanecen visibles por trazabilidad y no se cuentan como realizadas. Los valores de malestar, dificultad y comentarios son autoinformados y descriptivos; no constituyen una evaluación clínica automática.</p></article>
      <article className="mt-8"><h2 className="text-lg font-black text-[#171717]">Hallazgos estadísticos revisados</h2><p className="mt-2 text-xs leading-5 text-[#747474] print:hidden">Solo se incluyen si los seleccionás manualmente. Las sugerencias pendientes o descartadas nunca aparecen en el informe.</p>{reviewedSuggestions.length===0?<p className="mt-4 text-sm text-[#747474]">No hay sugerencias aceptadas o editadas para este ciclo.</p>:<div className="mt-4 space-y-3">{reviewedSuggestions.map(item=><label key={item.id} className={`block rounded-2xl border p-4 ${selectedSuggestionIds.includes(item.id)?'border-[#E8CE99] bg-[#F7F6F4]':'border-[#E9E7E7] bg-white print:hidden'}`}><span className="flex items-start gap-3"><input type="checkbox" className="mt-1 print:hidden" checked={selectedSuggestionIds.includes(item.id)} onChange={event=>setSelectedSuggestionIds(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><span><strong className="text-xs text-[#E49A02]">{item.ruleCode}</strong><span className="mt-1 block text-sm leading-6 text-[#2F2F2F]">{item.professionalText||item.summary}</span>{selectedSuggestionIds.includes(item.id)&&<small className="mt-2 block leading-5 text-[#8A5B00]">Limitación: {item.limitation}</small>}</span></span></label>)}</div>}</article>
      <label className="mt-8 block"><span className="text-lg font-black text-[#171717]">Resumen profesional</span><textarea className="mt-3 min-h-36 w-full rounded-2xl border border-[#E9E7E7] p-4 text-sm leading-6 print:border-0 print:p-0" value={summary} onChange={event=>setSummary(event.target.value)} placeholder="Texto redactado y revisado por el profesional…"/></label>
      <aside className="mt-8 rounded-2xl border border-[#E8CE99] bg-[#FFF7E8] p-4 text-xs leading-5 text-[#8A5B00]">ONUr organiza información y calcula resúmenes descriptivos. Este informe no diagnostica, no prescribe y debe ser revisado y firmado por un profesional habilitado.</aside>
    </section>{error&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952] print:hidden">{error}</p>}<div className="flex justify-end gap-3 print:hidden"><button type="button" onClick={()=>save('draft')} disabled={create.isPending} className="inline-flex items-center gap-2 rounded-2xl border border-[#E9E7E7] bg-white px-5 py-3 text-sm font-black text-[#2F2F2F]"><Save size={17}/> Guardar borrador</button><button type="button" onClick={()=>save('final')} disabled={create.isPending} className="inline-flex items-center gap-2 rounded-2xl bg-[#E49A02] px-5 py-3 text-sm font-black text-white"><FileCheck2 size={17}/> Versionar informe final</button></div>
  </div>
}
