import type { ExtractionFieldDefinition } from './types'

const posturography: ExtractionFieldDefinition[] = [
  { code: 'software_version', label: 'Software y versión', group: 'Estudio', studyType: 'posturography', aliases: ['software', 'version', 'posturografo'] },
  { code: 'study_date', label: 'Fecha del estudio', group: 'Estudio', studyType: 'posturography', required: true, aliases: ['fecha del estudio', 'fecha'] },
  { code: 'study_time', label: 'Hora', group: 'Estudio', studyType: 'posturography', aliases: ['hora'] },
  { code: 'duration', label: 'Duración', group: 'Estudio', studyType: 'posturography', aliases: ['duracion'] },
  { code: 'study_status', label: 'Estado del estudio', group: 'Estudio', studyType: 'posturography', aliases: ['estado'] },
  { code: 'scale', label: 'Escala', group: 'Estudio', studyType: 'posturography', aliases: ['escala'] },
  { code: 'last_name', label: 'Apellido impreso', group: 'Identidad', studyType: 'posturography', aliases: ['apellido'] },
  { code: 'first_name', label: 'Nombre impreso', group: 'Identidad', studyType: 'posturography', aliases: ['nombre'] },
  { code: 'reported_age', label: 'Edad al momento del estudio', group: 'Identidad', studyType: 'posturography', required: true, aliases: ['edad', 'edad al momento del estudio'] },
  { code: 'reported_sex', label: 'Sexo impreso', group: 'Identidad', studyType: 'posturography', aliases: ['sexo'] },
  { code: 'patient_id', label: 'Identificación impresa', group: 'Identidad', studyType: 'posturography', aliases: ['identificacion', 'id'] },
  { code: 'los_forward', label: 'Adelante', group: 'Límites de estabilidad', studyType: 'posturography', metricCode: 'los_forward', unitCode: 'deg', aliases: ['adelante', 'adel', 'forward'] },
  { code: 'los_backward', label: 'Atrás', group: 'Límites de estabilidad', studyType: 'posturography', metricCode: 'los_backward', unitCode: 'deg', aliases: ['atras', 'atr', 'backward'] },
  { code: 'los_left', label: 'Izquierda', group: 'Límites de estabilidad', studyType: 'posturography', metricCode: 'los_left', unitCode: 'deg', side: 'left', aliases: ['izquierda', 'izqui', 'left'] },
  { code: 'los_right', label: 'Derecha', group: 'Límites de estabilidad', studyType: 'posturography', metricCode: 'los_right', unitCode: 'deg', side: 'right', aliases: ['derecha', 'derech', 'right'] },
  { code: 'los_area', label: 'Área BAP', group: 'Límites de estabilidad', studyType: 'posturography', metricCode: 'los_area', unitCode: 'unknown', aliases: ['area'] },
  { code: 'selected_condition', label: 'Condición seleccionada', group: 'Límites de estabilidad', studyType: 'posturography', aliases: ['condicion seleccionada'] },
  { code: 'selected_area', label: 'Área de condición seleccionada', group: 'Límites de estabilidad', studyType: 'posturography', unitCode: 'unknown', aliases: ['area seleccionada'] },
  { code: 'sway_per_second_x', label: 'Sway/s X (anteroposterior)', group: 'Sway', studyType: 'posturography', metricCode: 'sway_per_second_x', unitCode: 'oscillations_per_second', aliases: ['sway/s x', 'sway s x', 'swayis x', 'balanceo/s x'] },
  { code: 'sway_per_second_y', label: 'Sway/s Y (lateral)', group: 'Sway', studyType: 'posturography', metricCode: 'sway_per_second_y', unitCode: 'oscillations_per_second', aliases: ['sway/s y', 'sway s y', 'swayis y', 'balanceo/s y'] },
  { code: 'sway_per_minute_x', label: 'Sway/m X (anteroposterior)', group: 'Sway', studyType: 'posturography', metricCode: 'sway_per_minute_x', unitCode: 'oscillations_per_minute', aliases: ['sway/m x', 'sway m x', 'swayim x', 'balanceo/m x'] },
  { code: 'sway_per_minute_y', label: 'Sway/m Y (lateral)', group: 'Sway', studyType: 'posturography', metricCode: 'sway_per_minute_y', unitCode: 'oscillations_per_minute', aliases: ['sway/m y', 'sway m y', 'swayim y', 'balanceo/m y'] },
  { code: 'afis_pattern', label: 'Control de calidad / patrón afisiológico', group: 'Resultados BAP', studyType: 'posturography', required: true, metricCode: 'aphysiological_pattern', unitCode: 'percent', aliases: ['patron afis.', 'patron afis', 'patron afisiologico', 'afis', 'calidad del estudio'] },
  { code: 'los_score', label: 'Score LOS', group: 'Resultados BAP', studyType: 'posturography', metricCode: 'los_score', unitCode: 'percent', aliases: ['score los', 'los score'] },
  { code: 'mix_ve_som', label: 'Def. Mix Ve Som', group: 'Resultados BAP derivados', studyType: 'posturography', aliases: ['def. mix ve som', 'mix ve som'] },
  { code: 'mix_ve_vi', label: 'Def. Mixto Ve Vi', group: 'Resultados BAP derivados', studyType: 'posturography', aliases: ['def. mixto ve vi', 'mixto ve vi'] },
  { code: 'pppd_index', label: 'Índice PPPD', group: 'Resultados BAP derivados', studyType: 'posturography', aliases: ['indice pppd', 'indice 3pd', 'pppd'] },
  ...Array.from({ length: 8 }, (_, index): ExtractionFieldDefinition => ({ code: `condition_area_${index + 1}`, label: `Área condición ${index + 1}`, group: 'Áreas de condiciones', studyType: 'posturography', unitCode: 'unknown', aliases: [`area condicion ${index + 1}`] })),
  ...Array.from({ length: 6 }, (_, index): ExtractionFieldDefinition => ({ code: `condition_${index + 1}`, label: `Condición ${index + 1}`, group: 'Condiciones', studyType: 'posturography', metricCode: 'condition_score', unitCode: 'percent', conditionCode: String(index + 1), required: true, aliases: [`condicion ${index + 1}`, `condition ${index + 1}`, `c${index + 1}`] })),
  { code: 'composite_score', label: 'Puntaje compuesto', group: 'Organización sensorial', studyType: 'posturography', required: true, metricCode: 'composite_score', unitCode: 'percent', aliases: ['compuesto', 'composite'] },
  { code: 'sensory_somatosensory', label: 'Índice somatosensorial', group: 'Organización sensorial', studyType: 'posturography', required: true, metricCode: 'sensory_ratio_somatosensory', unitCode: 'percent', aliases: ['somatosensorial'] },
  { code: 'sensory_visual', label: 'Índice visual', group: 'Organización sensorial', studyType: 'posturography', required: true, metricCode: 'sensory_ratio_visual', unitCode: 'percent', aliases: ['visual'] },
  { code: 'sensory_vestibular', label: 'Índice vestibular', group: 'Organización sensorial', studyType: 'posturography', required: true, metricCode: 'sensory_ratio_vestibular', unitCode: 'percent', aliases: ['vestibular'] },
  { code: 'visual_preference', label: 'Preferencia visual', group: 'Organización sensorial', studyType: 'posturography', required: true, metricCode: 'visual_preference_index', unitCode: 'percent', aliases: ['preferencia visual'] },
  { code: 'sensory_contribution_somatosensory', label: 'Contribución somatosensorial', group: 'Contribución sensorial', studyType: 'posturography', unitCode: 'percent', aliases: ['contribucion somatosensorial'] },
  { code: 'sensory_contribution_visual', label: 'Contribución visual', group: 'Contribución sensorial', studyType: 'posturography', unitCode: 'percent', aliases: ['contribucion visual'] },
  { code: 'sensory_contribution_vestibular', label: 'Contribución vestibular', group: 'Contribución sensorial', studyType: 'posturography', unitCode: 'percent', aliases: ['contribucion vestibular'] },
  { code: 'reported_conclusion', label: 'Resultado o conclusión profesional', group: 'Conclusión', studyType: 'posturography', metricCode: 'posturography_conclusion_text', aliases: ['resultado', 'conclusion', 'en suma'] },
]

const vestibular: ExtractionFieldDefinition[] = [
  { code: 'study_date', label: 'Fecha del estudio', group: 'Documento', studyType: 'vhit', required: true, aliases: ['fecha del estudio', 'fecha'] },
  { code: 'institution', label: 'Institución de origen', group: 'Documento', studyType: 'vhit', metricCode: 'institution_text', aliases: ['institucion', 'centro', 'clinica'] },
  { code: 'document_type', label: 'Tipo de documento', group: 'Documento', studyType: 'vhit', required: true, metricCode: 'document_type_text', aliases: ['tipo de documento'] },
  { code: 'professional', label: 'Profesional solicitante o informante', group: 'Documento', studyType: 'vhit', metricCode: 'professional_text', aliases: ['profesional', 'solicitante', 'informante'] },
  { code: 'referral_reason', label: 'Motivo de derivación', group: 'Antecedentes', studyType: 'vhit', metricCode: 'referral_reason_text', aliases: ['motivo de derivacion', 'motivo'] },
  { code: 'history', label: 'Antecedentes consignados', group: 'Antecedentes', studyType: 'vhit', metricCode: 'history_text', aliases: ['antecedentes'] },
  { code: 'symptoms', label: 'Síntomas descritos', group: 'Antecedentes', studyType: 'vhit', metricCode: 'symptoms_text', aliases: ['sintomas', 'sintomatologia'] },
  { code: 'evolution', label: 'Tiempo de evolución', group: 'Antecedentes', studyType: 'vhit', metricCode: 'evolution_text', aliases: ['tiempo de evolucion', 'evolucion'] },
  { code: 'clinical_exam', label: 'Examen clínico', group: 'Examen', studyType: 'vhit', metricCode: 'clinical_exam_text', aliases: ['examen clinico', 'examen'] },
  { code: 'test_device', label: 'Equipo, software y versión', group: 'Calidad técnica', studyType: 'vhit', aliases: ['equipo', 'dispositivo', 'software', 'version'] },
  { code: 'calibration_quality', label: 'Calibración, artefactos e interpretabilidad', group: 'Calidad técnica', studyType: 'vhit', aliases: ['calibracion', 'artefactos', 'calidad', 'interpretable'] },
  { code: 'himp', label: 'Protocolo HIMP', group: 'vHIT', studyType: 'vhit', required: true, metricCode: 'himp_text', aliases: ['himp'] },
  { code: 'shimp', label: 'SHIMP', group: 'vHIT', studyType: 'vhit', metricCode: 'shimp_text', aliases: ['shimp'] },
  { code: 'vhit_results', label: 'Resultados de vHIT', group: 'vHIT', studyType: 'vhit', metricCode: 'result_label', aliases: ['resultados vhit', 'vhit'] },
  { code: 'gain_method', label: 'Método o ventana de cálculo de ganancia', group: 'Calidad técnica', studyType: 'vhit', aliases: ['metodo de ganancia', 'gain method', 'regresion', '40 ms', '60 ms', '80 ms'] },
  { code: 'gain_right', label: 'Ganancia derecha', group: 'vHIT', studyType: 'vhit', required: true, metricCode: 'gain', unitCode: 'ratio', side: 'right', aliases: ['ganancia derecha', 'gain right', 'right gain', 'regresion od'] },
  { code: 'gain_left', label: 'Ganancia izquierda', group: 'vHIT', studyType: 'vhit', required: true, metricCode: 'gain', unitCode: 'ratio', side: 'left', aliases: ['ganancia izquierda', 'gain left', 'left gain', 'regresion oi'] },
  { code: 'symmetry', label: 'Simetría / asimetría', group: 'vHIT', studyType: 'vhit', required: true, metricCode: 'symmetry_text', aliases: ['simetria', 'asimetria'] },
  { code: 'saccades', label: 'Sacadas correctivas (overt/covert y repetibilidad)', group: 'vHIT', studyType: 'vhit', required: true, metricCode: 'saccade_present', aliases: ['sacadas correctivas', 'sacadas', 'saccades', 'overt', 'covert'] },
  { code: 'curves_channels', label: 'Plano y canales evaluados', group: 'Gráficos', studyType: 'vhit', required: true, metricCode: 'curves_channels_text', aliases: ['curvas', 'canales evaluados', 'canal', 'cull', 'lateral', 'horizontal'] },
  { code: 'impulse_counts', label: 'Cantidad de impulsos por lado', group: 'Calidad técnica', studyType: 'vhit', aliases: ['impulse nr', 'numero de impulsos', 'cantidad de impulsos', 'impulsos'] },
  { code: 'head_velocity', label: 'Velocidad de los impulsos cefálicos', group: 'Calidad técnica', studyType: 'vhit', aliases: ['head velocity', 'velocidad cefalica', 'velocidad de cabeza'] },
  { code: 'cranial_nerve_vii', label: 'VII par', group: 'Examen', studyType: 'vhit', metricCode: 'cranial_nerve_vii_text', aliases: ['vii par', 'septimo par'] },
  { code: 'fixation_system', label: 'Sistema de fijación', group: 'Examen', studyType: 'vhit', metricCode: 'fixation_system_text', aliases: ['sistema de fijacion', 'fijacion'] },
  { code: 'visual_suppression', label: 'Supresión visual', group: 'Examen', studyType: 'vhit', metricCode: 'visual_suppression_text', aliases: ['supresion visual'] },
  { code: 'skew', label: 'SKEW', group: 'Examen', studyType: 'vhit', metricCode: 'skew_text', aliases: ['skew'] },
  { code: 'head_shaking', label: 'Head Shaking Test', group: 'Examen', studyType: 'vhit', metricCode: 'head_shaking_text', aliases: ['head shaking test', 'head shaking'] },
  { code: 'vibration_test', label: 'Test vibracional', group: 'Examen', studyType: 'vhit', metricCode: 'vibration_test_text', aliases: ['test vibracional', 'vibracional'] },
  { code: 'vor_cancellation', label: 'Cancelación del VOR', group: 'Examen', studyType: 'vhit', metricCode: 'vor_cancellation_text', aliases: ['cancelacion del vor', 'vor cancellation'] },
  { code: 'positional_tests', label: 'Pruebas posicionales', group: 'Examen', studyType: 'vhit', metricCode: 'positional_tests_text', aliases: ['pruebas posicionales', 'posicionales'] },
  { code: 'gait', label: 'Marcha', group: 'Examen', studyType: 'vhit', metricCode: 'gait_text', aliases: ['marcha'] },
  { code: 'saccadic_precision', label: 'Precisión sacádica', group: 'Oculomotor', studyType: 'vhit', metricCode: 'saccadic_precision_text', aliases: ['precision sacadica', 'precision'] },
  { code: 'saccadic_velocity', label: 'Velocidad sacádica', group: 'Oculomotor', studyType: 'vhit', metricCode: 'saccade_velocity_deg_s', unitCode: 'deg_s', aliases: ['velocidad sacadica', 'velocidad'] },
  { code: 'smooth_pursuit', label: 'Seguimiento ocular lento', group: 'Oculomotor', studyType: 'vhit', metricCode: 'smooth_pursuit_text', aliases: ['seguimiento ocular lento', 'smooth pursuit'] },
  { code: 'deep_sensation', label: 'Sensibilidad profunda', group: 'Examen', studyType: 'vhit', metricCode: 'deep_sensation_text', aliases: ['sensibilidad profunda'] },
  { code: 'reflexes', label: 'Reflejos', group: 'Examen', studyType: 'vhit', metricCode: 'reflexes_text', aliases: ['reflejos'] },
  { code: 'conclusion', label: 'Conclusión o En suma', group: 'Conclusión', studyType: 'vhit', required: true, metricCode: 'reported_conclusion_text', aliases: ['conclusion', 'en suma'] },
  { code: 'conduct', label: 'Conducta', group: 'Conclusión', studyType: 'vhit', metricCode: 'conduct_text', aliases: ['conducta'] },
  { code: 'professional_observations', label: 'Observaciones profesionales', group: 'Conclusión', studyType: 'vhit', metricCode: 'professional_observations_text', aliases: ['observaciones profesionales', 'observaciones'] },
]

export const posturographyFieldDefinitions = posturography
export const vestibularFieldDefinitions = vestibular
