import type { StudyType } from '../studies/types'
import type { ExtractedField } from './types'

const reportRelevantCodes: Record<StudyType, ReadonlySet<string>> = {
  posturography: new Set([
    'study_date',
    'study_time',
    'last_name',
    'first_name',
    'reported_age',
    'reported_sex',
    'patient_id',
    'los_forward',
    'los_backward',
    'los_left',
    'los_right',
    'los_area',
    'selected_condition',
    'selected_area',
    'scale',
    'sway_per_second_x',
    'sway_per_second_y',
    'sway_per_minute_x',
    'sway_per_minute_y',
    'condition_area_1',
    'condition_area_2',
    'condition_area_3',
    'condition_area_4',
    'condition_area_5',
    'condition_area_6',
    'condition_area_7',
    'condition_area_8',
    'condition_1',
    'condition_2',
    'condition_3',
    'condition_4',
    'condition_5',
    'condition_6',
    'composite_score',
    'sensory_somatosensory',
    'sensory_visual',
    'sensory_vestibular',
    'visual_preference',
    'afis_pattern',
    'mix_ve_som',
    'mix_ve_vi',
    'pppd_index',
    'los_score',
    'sensory_contribution_somatosensory',
    'sensory_contribution_visual',
    'sensory_contribution_vestibular',
  ]),
  vhit: new Set([
    'study_date',
    'study_time',
    'patient_name',
    'reported_age',
    'patient_id',
    'institution',
    'document_type',
    'professional',
    'referral_reason',
    'history',
    'symptoms',
    'evolution',
    'clinical_exam',
    'test_device',
    'himp',
    'shimp',
    'vhit_results',
    'curves_channels',
    'gain_right',
    'gain_left',
    'gain_right_horizontal',
    'gain_left_horizontal',
    'gain_right_anterior',
    'gain_left_anterior',
    'gain_right_posterior',
    'gain_left_posterior',
    'gain_method',
    'symmetry',
    'saccades',
    'impulse_counts',
    'head_velocity',
    'calibration_quality',
    'cranial_nerve_vii',
    'fixation_system',
    'visual_suppression',
    'skew',
    'head_shaking',
    'vibration_test',
    'vor_cancellation',
    'positional_tests',
    'gait',
    'saccadic_precision',
    'saccadic_velocity',
    'smooth_pursuit',
    'deep_sensation',
    'reflexes',
    'conclusion',
    'conduct',
    'professional_observations',
  ]),
}

const reportRequiredCodes: Record<StudyType, ReadonlySet<string>> = {
  posturography: new Set([
    'study_date',
    'reported_age',
    'condition_1',
    'condition_2',
    'condition_3',
    'condition_4',
    'condition_5',
    'condition_6',
    'composite_score',
    'sensory_somatosensory',
    'sensory_visual',
    'sensory_vestibular',
    'visual_preference',
    'afis_pattern',
  ]),
  vhit: new Set([
    'himp',
    'curves_channels',
    'gain_right',
    'gain_left',
    'symmetry',
    'saccades',
  ]),
}

export function isReportRelevantField(field: Pick<ExtractedField, 'studyType' | 'code'>) {
  return reportRelevantCodes[field.studyType].has(field.code)
}

export function isReportRequiredField(field: Pick<ExtractedField, 'studyType' | 'code'> & Partial<Pick<ExtractedField, 'required'>>) {
  if (field.required !== undefined && field.studyType === 'vhit') return field.required
  return reportRequiredCodes[field.studyType].has(field.code)
}
