import { isSupabaseConfigured, supabase } from '../../lib/supabase'

export interface TreatmentReportRecord {id:string;patientId:string;patientName:string;treatmentCycleId:string;cycleLabel:string;version:number;status:'draft'|'final';professionalSummary:string;snapshot:Record<string,unknown>;createdAt:string;finalizedAt:string}
export interface CreateReportInput {patientId:string;treatmentCycleId:string;professionalSummary:string;snapshot:Record<string,unknown>;status:'draft'|'final'}
const STORAGE_KEY='onur-demo-reports-v1'
function read(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return[] as TreatmentReportRecord[];try{return JSON.parse(raw) as TreatmentReportRecord[]}catch{return[]}}
function write(items:TreatmentReportRecord[]){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function fromRow(row:Record<string,unknown>):TreatmentReportRecord{const patient=(row.patients??{}) as Record<string,unknown>;const cycle=(row.treatment_cycles??{}) as Record<string,unknown>;return{id:String(row.id),patientId:String(row.patient_id),patientName:String(patient.full_name??''),treatmentCycleId:String(row.treatment_cycle_id),cycleLabel:String(cycle.label??''),version:Number(row.version),status:row.status as 'draft'|'final',professionalSummary:String(row.professional_summary??''),snapshot:(row.snapshot??{}) as Record<string,unknown>,createdAt:String(row.created_at),finalizedAt:String(row.finalized_at??'')}}
const select='*, patients(full_name), treatment_cycles(label)'
export async function listPatientReports(patientId:string):Promise<TreatmentReportRecord[]>{if(!isSupabaseConfigured||!supabase)return read().filter(item=>item.patientId===patientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const{data,error}=await supabase.from('treatment_reports').select(select).eq('patient_id',patientId).order('created_at',{ascending:false});if(error)throw error;return(data??[]).map(fromRow)}
export async function listProfessionalReports():Promise<TreatmentReportRecord[]>{if(!isSupabaseConfigured||!supabase)return read().sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const{data,error}=await supabase.from('treatment_reports').select(select).order('created_at',{ascending:false});if(error)throw error;return(data??[]).map(fromRow)}
export async function createTreatmentReport(input:CreateReportInput):Promise<TreatmentReportRecord>{
  if(!isSupabaseConfigured||!supabase){const existing=read();const version=Math.max(0,...existing.filter(item=>item.treatmentCycleId===input.treatmentCycleId).map(item=>item.version))+1;const patient=(input.snapshot.patient??{}) as Record<string,unknown>;const cycle=(input.snapshot.cycle??{}) as Record<string,unknown>;const record:TreatmentReportRecord={id:crypto.randomUUID(),patientId:input.patientId,patientName:String(patient.fullName??'Paciente'),treatmentCycleId:input.treatmentCycleId,cycleLabel:String(cycle.label??'Ciclo'),version,status:input.status,professionalSummary:input.professionalSummary,snapshot:input.snapshot,createdAt:new Date().toISOString(),finalizedAt:input.status==='final'?new Date().toISOString():''};write([...existing,record]);return record}
  const{data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw authError??new Error('Sesión profesional no disponible.');const{data:latest}=await supabase.from('treatment_reports').select('version').eq('treatment_cycle_id',input.treatmentCycleId).order('version',{ascending:false}).limit(1).maybeSingle();const version=(latest?.version??0)+1;const{data,error}=await supabase.from('treatment_reports').insert({patient_id:input.patientId,treatment_cycle_id:input.treatmentCycleId,version,status:input.status,professional_summary:input.professionalSummary||null,snapshot:input.snapshot,created_by:auth.user.id,finalized_at:input.status==='final'?new Date().toISOString():null}).select(select).single();if(error)throw error;return fromRow(data)
}
